apiVersion: v1
kind: Service
metadata:
  name: demoapp1
  namespace: demo
spec:
  type: LoadBalancer
  selector:
    app: demoapp1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 30010
      nodePort: 30008
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: demoapp1
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoapp1
  template:
    metadata:
      labels:
        app: demoapp1
    spec:
      containers:
        - name: demoapp1
          image: demoapp
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 30010

